name: TurnPro CI

on:
  pull_request:

jobs:
  build:
    name: Run Unit Tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch_depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install Dependencies
        run: yarn

      - name: Tests
        run: yarn tests